Repository pylover/restfulpy, pull requests merged in 2019-02, with the labels that each got.

#284 Fixing a bug on the json patch controller mixin
  restfulpy/controllers.py
  restfulpy/tests/test_jsonpatch.py
Labels: bug

#287 Fixing a bug on the simple scaffold related to the tests
  restfulpy/scaffolding/templates/simple/__project__/tests/test_foo.py.template
Labels: bug

#288 Add __exclude__ list to modified mixin
  restfulpy/orm/mixins.py
  restfulpy/tests/test_modified_mixin.py
Labels: feature

#289 Fix a bug on modified mixin
  restfulpy/orm/mixins.py
  restfulpy/tests/test_modified_mixin.py
  restfulpy/tests/test_to_json_field_info.py
Labels: bug

#291 JSON Patch Form Length
  restfulpy/controllers.py
  restfulpy/tests/test_jsonpatch.py
Labels: bug

#294 Migrating to bddrest => 2.2.1
  setup.py
Labels: deployment

#293 Migrating to nanohttp => 1.10.5
  setup.py
Labels: deployment

#298 The serve cli is removed
  restfulpy/application/cli/main.py
  restfulpy/application/cli/serve.py
Labels: enhancement
