Repository pylover/restfulpy, pull requests merged in 2019-06, with the labels that each got.

#328 Added new test case to the Date-time test
  tests/test_datetime.py
Labels: enhancement

#325 The scope of db fixture has changed from module to function
  restfulpy/testing.py
Labels: bug

#326 The scope of db fixture has changed from module to function
  restfulpy/testing.py
Labels: bug

#327 Removed the deprecated method from the db fixture
  restfulpy/testing.py
Labels: enhancement

#330 Purged the deprecated decorator from the utils module
  restfulpy/utils.py
Labels: purge

#329 Added new test case related to the split URL
  tests/test_utils.py
Labels: enhancement

#331 Revert 'Remove IS NULL and IS NOT NULL from filtering mixin'
  restfulpy/orm/mixins.py
  tests/test_mixin_filtering.py
Labels: bug
