Repository pylover/restfulpy, pull requests merged in 2019-03, with the labels that each got.

#304 Fixed commit on 2xx and 3xx statuses
  restfulpy/orm/__init__.py
  restfulpy/tests/test_commit_decorator.py
Labels: bug

#306 Removal the ERD generator, closes #302
  restfulpy/application/cli/erd.py
  restfulpy/application/cli/main.py
Labels: purge

#310 The main cli is migrated to the easycli
  restfulpy/cli.py
  restfulpy/scaffolding/launchers.py
Labels: migrate

#307 Fixed commit decorator rollbacked on 2xx and 3xx statuses (#304)
  restfulpy/orm/__init__.py
  restfulpy/tests/test_commit_decorator.py
Labels: bug

#312 Fixed a bug on the application module related to the root controller
  restfulpy/application/__init__.py
Labels: bug

#313 Tested the jwt cli
  restfulpy/application/cli/jwttoken.py
  restfulpy/tests/test_jwt_cli.py
Labels: enhancement
